name: Deploy shyk

on:
    workflow_dispatch:
    release:
        types: [published]
    push:
        branches:
            - prod

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            
            - name: Run GetEnv command
              uses: DovnarAlexander/github-actions-jelastic@master
              with:
                jelastic_url: https://app.jpc.infomaniak.com/
                jelastic_username: ${{ secrets.JELASTIC_USERNAME }}
                jelastic_password: ${{ secrets.JELASTIC_TOKEN }}
                task: environment/vcs/update --envName shyk-prod --context ROOT
