name: Deploy shyk

on:
    workflow_dispatch:
    release:
        types: [published]
    push:
        branches:
            - prod

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Download Jelastic CLI
              run: curl -s ftp://ftp.jelastic.com/pub/cli/jelastic-cli-installer.sh | bash
          
            - name: Login to Jelastic
              run: ~/jelastic/users/authentication/signin --login  ${{ secrets.JELASTIC_USERNAME }} --password  ${{ secrets.JELASTIC_TOKEN }} --platformUrl  https://app.jpc.infomaniak.com/
 
            - name: Pull from GitHub, build and deploy
              run: ~/jelastic/environment/vcs/update --envName shyk-prod --context ROOT
